# earmarks vs. disaster risk

Brazilian lawmakers direct billions in earmarked funds to specific places. Part of this money is related to climate mitigation and adaptation. this project aims to find if this distribution follows evidence regarding projected risk or past climate events for flood and landslide. I rebuilt this notebook to reorganize it after several mistakes were made in an earlier version

In [10]:
import os
import pandas as pd

## earmarks table
Downloaded from Portal da Transparência

In [11]:
emendas = pd.read_csv('data/dados_brutos/EmendasParlamentares.csv', sep=';', encoding='latin1')
emendas.head()

/var/folders/n_/3j3vmvq51gz0dc6g0xjknkm80000gn/T/ipykernel_27345/735340104.py:1: DtypeWarning: Columns (0: Código da Emenda, 1: Código do Autor da Emenda, 2: Número da emenda) have mixed types. Specify dtype option on import or set low_memory=False.
  emendas = pd.read_csv('data/dados_brutos/EmendasParlamentares.csv', sep=';', encoding='latin1')

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
0,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,FEIJÓ - AC,1200302,FEIJÓ,1200000,...,7652,IMPLANTACAO DE MELHORIAS SANITARIAS DOMICILIAR...,0000,IMPLANTACAO DE MELHORIAS SANITARIAS DOMICILIAR...,"250000,00","0,00","0,00","0,00","250000,00","0,00"
1,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,MINAS GERAIS (UF),Sem informação,Sem informação,3100000,...,14UF,"CONSTRUCAO, REFORMA, EQUIPAGEM E AMPLIACAO DE ...",0000,"CONSTRUCAO, REFORMA, EQUIPAGEM E AMPLIACAO DE ...","3143341,40","0,00","0,00","830201,40","830201,40","2313140,00"
2,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,COMODORO - MT,5103304,COMODORO,5100000,...,20ZV,FOMENTO AO SETOR AGROPECUARIO,0000,FOMENTO AO SETOR AGROPECUARIO - DESPESAS DIVERSAS,"243750,00","0,00","0,00","0,00","0,00","243750,00"
3,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,PINDAMONHANGABA - SP,3538006,PINDAMONHANGABA,3500000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"159644,37","0,00","0,00","0,00","0,00","159644,37"
4,Sem informação,2014,Emenda Individual - Transferências com Finalid...,S/I,Sem informação,S/I,SOBRADO - PB,2515971,SOBRADO,2500000,...,8581,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO PR...,0000,ESTRUTURACAO DA REDE DE SERVICOS DE ATENCAO BA...,"379000,00","0,00","0,00","0,00","0,00","379000,00"

In [12]:
#2023-2026, fixing dots, commas
emendas = emendas[emendas['Ano da Emenda'].isin([2023, 2024, 2025, 2026])]
emendas["Ano da Emenda"].unique()

array([2023, 2024, 2025, 2026])

In [13]:
emendas['Valor Empenhado'] = emendas['Valor Empenhado'].str.replace('.','').str.replace(',','.').astype(float)
emendas.head()

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
69583,202338950001,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,1,CORAÇÃO DE MARIA - BA,2908903,CORAÇÃO DE MARIA,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,1500000.0,"1500000,00","1500000,00","0,00","0,00","0,00"
69584,202338950002,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,2,CORIBE - BA,2909109,CORIBE,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,2000000.0,"2000000,00","2000000,00","0,00","0,00","0,00"
69585,202338950003,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,3,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,8218164.0,"8218164,00","8218164,00","0,00","0,00","0,00"
69586,202338950004,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,4,ITATIM - BA,2916856,ITATIM,2900000,...,2E90,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,600000.0,"600000,00","600000,00","0,00","0,00","0,00"
69587,202338950005,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,5,SANTA TERESINHA - BA,2928505,SANTA TERESINHA,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,1500000.0,"1500000,00","1500000,00","0,00","0,00","0,00"

## environmental filter

Inesc published a report on climate financing that lists 97 budget action codes for environmental work

In [14]:
from natural_pdf import PDF

pdf = PDF('data/dados_brutos/inesc.pdf')
len(pdf.pages)

58

In [15]:
table = pdf.pages[25].extract_table()
for row in table:
    print(row)

['ento\nRegional', 'Desastre\ns', 'Defesa Civil\npara a\nEstruturação\ndo Órgão\nCoordenador\ndo Sistema\nFederal de\nProteção e\nDefesa Civil', '', '']
['53000 -\nMinistério da\nIntegração e\ndo\nDesenvolvim\nento\nRegional', '2318 -\nGestão\nde\nRiscos e\nde\nDesastre\ns', '22BO - Ações\nde Proteção e\nDefesa Civil', '800.00\n0.000', '100']
['53000 -\nMinistério da\nIntegração e\ndo\nDesenvolvim\nento\nRegional', '2318 -\nGestão\nde\nRiscos e\nde\nDesastre\ns', '8172 -\nCoordenação e\nFortalecimento\ndo Sistema\nNacional de\nProteção e\nDefesa Civil\n(SINPDEC)', '10.600.\n000', '5.391.800']
['53000 -\nMinistério da\nIntegração e\ndo\nDesenvolvim', '2318 -\nGestão\nde\nRiscos e\nde', '8348 - Apoio às\nAções\nEmergenciais\nde Prevenção e\nMitigação para', '600.00\n0', '600.100']

In [16]:
table = pdf.pages[25].extract_table(method="text")
for row in table:
    print(row)

[None, None, None, None, None]
[None, None, None, None, None]
['ento', 'Desastre', 'Defesa Civil', None, None]
['Regional', 's', 'para a', None, None]
[None, None, 'Estruturação', None, None]
[None, None, 'do Órgão', None, None]
[None, None, 'Coordenador', None, None]
[None, None, 'do Sistema', None, None]
[None, None, 'Federal de', None, None]
[None, None, 'Proteção e', None, None]
[None, None, 'Defesa Civil', None, None]
[None, None, None, None, None]
['53000 -', '2318 -', '22BO - Ações', '800.00', '100']
['Ministério da', 'Gestão', 'de Proteção e', '0.000', None]
['Integração e', 'de', 'Defesa Civil', None, None]
['do', 'Riscos e', None, None, None]
['Desenvolvim', 'de', None, None, None]
['ento', 'Desastre', None, None, None]
['Regional', 's', None, None, None]
[None, None, None, None, None]
['53000 -', '2318 -', '8172 -', '10.600.', '5.391.800']
['Ministério da', 'Gestão', 'Coordenação e', '000', None]
['Integração e', 'de', 'Fortalecimento', None, None]
['do', 'Riscos e', 'do Sistema', None, None]
['Desenvolvim', 'de', 'Nacional de', None, None]
['ento', 'Desastre', 'Proteção e', None, None]
['Regional', 's', 'Defesa Civil', None, None]
[None, None, '(SINPDEC)', None, None]
[None, None, None, None, None]
['53000 -', '2318 -', '8348 - Apoio às', '600.00', '600.100']
['Ministério da', 'Gestão', 'Ações', '0', None]
['Integração e', 'de', 'Emergenciais', None, None]
['do', 'Riscos e', 'de Prevenção e', None, None]
['Desenvolvim', 'de', 'Mitigação para', None, None]

In [18]:
#classified codes (dont put me in prision!!!!) 
codigos = ["20G4", "20VA", "20VY", "216W", "21E4", "00UD", "20VP", "21F1", "21F2", "10TT", "20WH", "21A9", "6925", "21HR", "000K", "00T5", "00TK", "20GB", "21HC", "21HP", "21HQ", "22BO", "8172", "8348", "8865", "00LX", "00T6", "00T7", "00T8", "00T9", "00TA", "00TB", "00TG", "00UN", "00VA", "00WP", "11AA", "12EP", "14VI", "152D", "15DX", "15XT", "15XV", "15XW", "15ZK", "162K", "166K", "169E", "1N64", "20N4", "20VR", "20VS", "20WI", "214T", "219H", "21DD", "21DE", "21DF", "21DG", "21HX", "2378", "4926", "5308", "5900", "7G88", "7M12", "7X91", "7XZ4", "00UO", "219R", "4909", "00SY", "8872", "8874", "00SW", "00T2", "00TH", "00TJ", "00VC", "00VD", "168N", "20W2", "20WM", "20WN", "214M", "214N", "214O", "214P", "218R", "219K", "21F3", "21F4", "21F5", "21HJ", "21HK", "21I5", "2E87"]
len(codigos)

97

In [19]:
#How many earmarks are environmental?
ambientais = emendas[emendas['Código Ação'].isin(codigos)]
ambientais.head()

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
69799,202327760019,2023,Emenda Individual - Transferências com Finalid...,2776,ALESSANDRO MOLON,19,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,20WM,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",0000,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",488667.88,"0,00","0,00","12805,02","0,00","475862,86"
69899,202330420002,2023,Emenda Individual - Transferências com Finalid...,3042,ALTINEU CORTES,2,SÃO GONÇALO - RJ,3304904,SÃO GONÇALO,3300000,...,00SY,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",0000,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",12219069.00,"518333,00","518333,00","11700736,00","0,00","0,00"
69942,202310740007,2023,Emenda Individual - Transferências com Finalid...,1074,ANDRE DE PAULA,7,ITAPISSUMA - PE,2607752,ITAPISSUMA,2600000,...,00T5,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",0000,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",500000.00,"0,00","0,00","143976,05","0,00","356023,95"
69959,202320830015,2023,Emenda Individual - Transferências com Finalid...,2083,ANDRE FIGUEIREDO,15,RUSSAS - CE,2311801,RUSSAS,2300000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,250000.00,"0,00","0,00","70400,00","0,00","179600,00"
70021,202339150004,2023,Emenda Individual - Transferências com Finalid...,3915,AROLDO MARTINS,4,PARANÁ (UF),Sem informação,Sem informação,4100000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,162920.00,"0,00","0,00","0,00","0,00","162920,00"

In [20]:
#cities
ambientais['Município']

69799    Sem informação
69899       SÃO GONÇALO
69942        ITAPISSUMA
69959            RUSSAS
70021    Sem informação
              ...
93683    Sem informação
93693    RIO DE JANEIRO
93805    CAMPINA GRANDE
93873    Sem informação
93894            CUIABÁ
Name: Município, Length: 269, dtype: str

## Risk scores from AdaptaBrasil
landslide and floods as indicators

In [25]:
import requests
url ="https://sistema.adaptabrasil.mcti.gov.br/api/hierarquia/adaptabrasil"
response = requests.get(url).json()
len(response)

558

In [26]:
response[0]

{'id': 0,
 'name': 'Base conceitual conforme definições\xa0do\xa0IPCC',
 'title': 'Risco Climático',
 'shortname': 'Risco Climático',
 'simple_description': 'Base conceitual conforme definições\xa0do\xa0IPCC',
 'complete_description': '<html><p><img src="https://s3.us-east-1.amazonaws.com/cache-sistema.adaptabrasil.dev.apps.rnp.br/imagens/flor-de-risco3.png" alt="Riscos"><br>\nNo AdaptaBrasil&comma; o risco clim&aacute;tico combina tr&ecirc;s fatores: Amea&ccedil;a clim&aacute;tica&comma; Exposi&ccedil;&atilde;o e Vulnerabilidade. A Amea&ccedil;a clim&aacute;tica &eacute; a possibilidade de acontecerem eventos extremos&comma; como chuvas fortes&comma; enchentes ou secas&comma; capazes de causar  perdas econ&ocirc;micas&comma; impactos ambientais ou at&eacute; colocar vidas em risco. Esses efeitos podem variar de acordo com o setor analisado. A Exposi&ccedil;&atilde;o refere-se &agrave; exist&ecirc;ncia de elementos aos quais a amea&ccedil;a clim&aacute;tica pode causar danos&comma; sejam eles pessoas&comma; esp&eacute;cies&comma; ecossistemas ou infraestruturas. A Vulnerabilidade indica a predisposi&ccedil;&atilde;o de uma &aacute;rea ser afetada pelos impactos das mudan&ccedil;as do clima&comma; sendo composta pela Sensibilidade (o quanto a &aacute;rea pode ser imediatamente afetada pela amea&ccedil;a clim&aacute;tica)&comma; e pela Capacidade adaptativa (a habilidade de se preparar&comma; reagir e se adaptar &agrave; amea&ccedil;a clim&aacute;tica&comma; seja prevenindo os riscos ou reduzindo os impactos depois que eles ocorrem). O &Iacute;ndice de Risco Clim&aacute;tico &eacute; calculado para cada setor e munic&iacute;pio do Brasil. Para mais informa&ccedil;&otilde;es&comma;&nbsp;clique <a href="https://www.youtube.com/watch?v=-9rgniOaViM" target="_blank">aqui</a>.</html>',
 'equation': None,
 'level': 0,
 'pessimist': None,
 'indicator_id_master': 'None',
 'years': [],
 'years_description': None,
 'scenarios': None,
 'imageurl': None,
 'sep_id': None,
 'sep_description': None,
 'disturbance': None,
 'geometrytype': 'MultiPolygon',
 'measurement_unit': None,
 'climate_hazard': None,
 'legend': None,
 'menu_structure': None,
 'color': '#FFFFFF'}

In [32]:
dados = response

In [34]:
import pandas as pd

riskadapta = pd.DataFrame(dados)

riskadapta.head()

,id,name,title,shortname,simple_description,complete_description,equation,level,pessimist,indicator_id_master,...,imageurl,sep_id,sep_description,disturbance,geometrytype,measurement_unit,climate_hazard,legend,menu_structure,color
0,0,Base conceitual conforme definições do IPCC,Risco Climático,Risco Climático,Base conceitual conforme definições do IPCC,"<html><p><img src=""https://s3.us-east-1.amazon...",None,0,NaN,None,...,NaN,NaN,NaN,None,MultiPolygon,None,None,None,None,#FFFFFF
1,1,Recursos hídricos,Impactos para recursos hídricos,Recursos hídricos,Consequências esperadas e resultantes das muda...,"São os efeitos sobre vidas, meios de subsistên...",None,1,NaN,0,...,https://s3.sa-east-1.amazonaws.com/cache-siste...,1.0,"<div className=""raiz-text""><span className=""ra...",None,MultiPolygon,None,None,None,"{'defaultclippingresolution': {'id': 1, 'cid':...",NaN
2,5000,Segurança alimentar,Impactos para segurança alimentar,Segurança alimentar,Consequências esperadas e resultantes das muda...,"Os impactos sobre vidas, meios de subsistência...",None,1,1.0,0,...,https://s3.sa-east-1.amazonaws.com/cache-siste...,2.0,"<div className=""raiz-text""><span className=""ra...",None,MultiPolygon,None,None,"{'items': [{'order': 1, 'label': 'Muito baixo'...","{'defaultclippingresolution': {'id': 1, 'cid':...",NaN
3,10000,Segurança energética,Impactos para segurança energética,Segurança energética,Consequências esperadas e resultantes das muda...,"São os efeitos sobre vidas, meios de subsistên...",None,1,1.0,0,...,https://s3.sa-east-1.amazonaws.com/cache-siste...,3.0,"<div className=""raiz-text""><span className=""ra...",None,MultiPolygon,None,None,"{'items': [{'order': 1, 'label': 'Muito baixo'...","{'defaultclippingresolution': {'id': 1, 'cid':...",NaN
4,40000,Infraestrutura portuária,Impactos para infraestrutura portuária,Infraestrutura portuária,Consequências esperadas e resultantes das muda...,"São os efeitos sobre vidas, meios de subsistên...",None,1,1.0,0,...,https://s3.sa-east-1.amazonaws.com/cache-siste...,4.0,"<div className=""raiz-text""><span className=""ra...",None,MultiPoint,None,None,"{'items': [{'order': 1, 'label': 'Muito baixo'...","{'defaultclippingresolution': {'id': 4, 'cid':...",NaN

In [35]:
for item in response:
    if 'eslizamento' in item['name'] or 'nundaç' in item['name']:
        print(item['name'])

Deslizamento de terra
Inundações, enxurradas e alagamentos
Alagamento e inundação
Deslizamento
Deslizamento
Vulnerabilidade à inundação
Suscetibilidade a deslizamentos
Suscetibilidade a deslizamentos

In [36]:
for item in response:
    if 'eslizamento' in item['name'] or 'nundaç' in item['name']:
        print(item['id'], item['name'])

60001 Deslizamento de terra
60041 Inundações, enxurradas e alagamentos
70001 Alagamento e inundação
70014 Deslizamento
80001 Deslizamento
70005 Vulnerabilidade à inundação
70018 Suscetibilidade a deslizamentos
80005 Suscetibilidade a deslizamentos

In [37]:
for item in response:
    if item['id'] in [60001, 60041]:
        print(item['id'], item['years'])

60001 [2015, 2030, 2050]
60041 [2015, 2030, 2050]

## Scores

API AdaptaBrasil
'/mapa-dados/BR/municipio/{indicator}/{year}/{scenario}/adaptabrasil'

In [38]:
url = "https://sistema.adaptabrasil.mcti.gov.br/api/mapa-dados/BR/municipio/60001/2030/null/adaptabrasil"
teste = requests.get(url).json()
len(teste)

0

In [39]:
url = "https://sistema.adaptabrasil.mcti.gov.br/api/mapa-dados/BR/municipio/60001/2015/null/adaptabrasil"
deslizamento =pd.DataFrame(requests.get(url).json())

deslizamento.shape

(5570, 10)

In [41]:
url = "https://sistema.adaptabrasil.mcti.gov.br/api/mapa-dados/BR/municipio/60041/2015/null/adaptabrasil"
inundacao = pd.DataFrame(requests.get(url).json())
inundacao.shape

(5570, 10)

In [42]:
deslizamento.head()

,id,geocod_ibge,name,indicator_id,year,scenario_id,pessimist,value,valuecolor,rangelabel
0,2644,5200050,Abadia de Goiás/GO,60001,2015,None,1,0.12,#02C650,Muito baixo
1,754,3100104,Abadia dos Dourados/MG,60001,2015,None,1,0.54,#FFCD00,Médio
2,2645,5200100,Abadiânia/GO,60001,2015,None,1,0.49,#FFCD00,Médio
3,755,3100203,Abaeté/MG,60001,2015,None,1,0.40,#FFCD00,Médio
4,2938,1500107,Abaetetuba/PA,60001,2015,None,1,0.48,#FFCD00,Médio

In [43]:
inundacao.head()

,id,geocod_ibge,name,indicator_id,year,scenario_id,pessimist,value,valuecolor,rangelabel
0,2644,5200050,Abadia de Goiás/GO,60041,2015,None,1,0.19,#02C650,Muito baixo
1,754,3100104,Abadia dos Dourados/MG,60041,2015,None,1,0.60,#FF8300,Alto
2,2645,5200100,Abadiânia/GO,60041,2015,None,1,0.47,#FFCD00,Médio
3,755,3100203,Abaeté/MG,60041,2015,None,1,0.51,#FFCD00,Médio
4,2938,1500107,Abaetetuba/PA,60041,2015,None,1,0.78,#FF8300,Alto

## risk + environmental money

In [44]:
%whos DataFrame

Variable       Type         Data/Info
-------------------------------------
ambientais     DataFrame    Shape: (269, 28)
deslizamento   DataFrame    Shape: (5570, 10)
emendas        DataFrame    Shape: (24493, 28)
inundacao      DataFrame    Shape: (5570, 10)
riskadapta     DataFrame    Shape: (558, 23)
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [45]:
ambientais.head()

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
69799,202327760019,2023,Emenda Individual - Transferências com Finalid...,2776,ALESSANDRO MOLON,19,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,20WM,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",0000,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",488667.88,"0,00","0,00","12805,02","0,00","475862,86"
69899,202330420002,2023,Emenda Individual - Transferências com Finalid...,3042,ALTINEU CORTES,2,SÃO GONÇALO - RJ,3304904,SÃO GONÇALO,3300000,...,00SY,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",0000,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",12219069.00,"518333,00","518333,00","11700736,00","0,00","0,00"
69942,202310740007,2023,Emenda Individual - Transferências com Finalid...,1074,ANDRE DE PAULA,7,ITAPISSUMA - PE,2607752,ITAPISSUMA,2600000,...,00T5,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",0000,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",500000.00,"0,00","0,00","143976,05","0,00","356023,95"
69959,202320830015,2023,Emenda Individual - Transferências com Finalid...,2083,ANDRE FIGUEIREDO,15,RUSSAS - CE,2311801,RUSSAS,2300000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,250000.00,"0,00","0,00","70400,00","0,00","179600,00"
70021,202339150004,2023,Emenda Individual - Transferências com Finalid...,3915,AROLDO MARTINS,4,PARANÁ (UF),Sem informação,Sem informação,4100000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,162920.00,"0,00","0,00","0,00","0,00","162920,00"

In [46]:
riscos = deslizamento.merge(inundacao, on='geocod_ibge', suffixes=('_deslizamento', '_inundacao'))

ambiental_cidades = ambientais.groupby('Código Município IBGE')['Valor Empenhado'].sum().reset_index()

df_final = riscos.merge(ambiental_cidades, left_on='geocod_ibge', right_on='Código Município IBGE', how='left')
df_final.shape

(5570, 21)

In [47]:
df_final.head()

,id_deslizamento,geocod_ibge,name_deslizamento,indicator_id_deslizamento,year_deslizamento,scenario_id_deslizamento,pessimist_deslizamento,value_deslizamento,valuecolor_deslizamento,rangelabel_deslizamento,...,name_inundacao,indicator_id_inundacao,year_inundacao,scenario_id_inundacao,pessimist_inundacao,value_inundacao,valuecolor_inundacao,rangelabel_inundacao,Código Município IBGE,Valor Empenhado
0,2644,5200050,Abadia de Goiás/GO,60001,2015,None,1,0.12,#02C650,Muito baixo,...,Abadia de Goiás/GO,60041,2015,None,1,0.19,#02C650,Muito baixo,NaN,NaN
1,754,3100104,Abadia dos Dourados/MG,60001,2015,None,1,0.54,#FFCD00,Médio,...,Abadia dos Dourados/MG,60041,2015,None,1,0.60,#FF8300,Alto,NaN,NaN
2,2645,5200100,Abadiânia/GO,60001,2015,None,1,0.49,#FFCD00,Médio,...,Abadiânia/GO,60041,2015,None,1,0.47,#FFCD00,Médio,NaN,NaN
3,755,3100203,Abaeté/MG,60001,2015,None,1,0.40,#FFCD00,Médio,...,Abaeté/MG,60041,2015,None,1,0.51,#FFCD00,Médio,NaN,NaN
4,2938,1500107,Abaetetuba/PA,60001,2015,None,1,0.48,#FFCD00,Médio,...,Abaetetuba/PA,60041,2015,None,1,0.78,#FF8300,Alto,NaN,NaN

In [48]:
df_final = df_final.drop(columns=['id_deslizamento', 'indicator_id_deslizamento', 'year_deslizamento', 'scenario_id_deslizamento', 'pessimist_deslizamento', 'id_inundacao', 'name_inundacao', 'indicator_id_inundacao', 'year_inundacao', 'scenario_id_inundacao', 'pessimist_inundacao', 'Código Município IBGE'])
df_final.columns.tolist()

['geocod_ibge',
 'name_deslizamento',
 'value_deslizamento',
 'valuecolor_deslizamento',
 'rangelabel_deslizamento',
 'value_inundacao',
 'valuecolor_inundacao',
 'rangelabel_inundacao',
 'Valor Empenhado']

In [49]:
df_final= df_final.rename(columns={'geocod_ibge': 'Código IBGE','name_deslizamento': 'Município','value_deslizamento': 'Índice Deslizamento','valuecolor_deslizamento': 'Cor Deslizamento','rangelabel_deslizamento': 'Label Deslizamento','value_inundacao': 'Índice Inundação','valuecolor_inundacao': 'Cor Inundação','rangelabel_inundacao': 'Label Inundação'})

df_final.head()

,Código IBGE,Município,Índice Deslizamento,Cor Deslizamento,Label Deslizamento,Índice Inundação,Cor Inundação,Label Inundação,Valor Empenhado
0,5200050,Abadia de Goiás/GO,0.12,#02C650,Muito baixo,0.19,#02C650,Muito baixo,NaN
1,3100104,Abadia dos Dourados/MG,0.54,#FFCD00,Médio,0.60,#FF8300,Alto,NaN
2,5200100,Abadiânia/GO,0.49,#FFCD00,Médio,0.47,#FFCD00,Médio,NaN
3,3100203,Abaeté/MG,0.40,#FFCD00,Médio,0.51,#FFCD00,Médio,NaN
4,1500107,Abaetetuba/PA,0.48,#FFCD00,Médio,0.78,#FF8300,Alto,NaN

## risk per city
following AdaptaBrasil lables

In [50]:
df_final

,Código IBGE,Município,Índice Deslizamento,Cor Deslizamento,Label Deslizamento,Índice Inundação,Cor Inundação,Label Inundação,Valor Empenhado
0,5200050,Abadia de Goiás/GO,0.12,#02C650,Muito baixo,0.19,#02C650,Muito baixo,NaN
1,3100104,Abadia dos Dourados/MG,0.54,#FFCD00,Médio,0.60,#FF8300,Alto,NaN
2,5200100,Abadiânia/GO,0.49,#FFCD00,Médio,0.47,#FFCD00,Médio,NaN
3,3100203,Abaeté/MG,0.40,#FFCD00,Médio,0.51,#FFCD00,Médio,NaN
4,1500107,Abaetetuba/PA,0.48,#FFCD00,Médio,0.78,#FF8300,Alto,NaN
...,...,...,...,...,...,...,...,...,...
5565,2933604,Xique-Xique/BA,0.60,#FF8300,Alto,0.72,#FF8300,Alto,NaN
5566,2517407,Zabelê/PB,0.57,#FFCD00,Médio,0.62,#FF8300,Alto,NaN
5567,3557154,Zacarias/SP,0.12,#02C650,Muito baixo,0.26,#A9DE00,Baixo,NaN
5568,2114007,Zé Doca/MA,0.61,#FF8300,Alto,0.83,#F40000,Muito alto,NaN
5569,4219853,Zortéa/SC,0.23,#A9DE00,Baixo,0.33,#A9DE00,Baixo,NaN

In [53]:
df_final['Índice Risco Médio'] =(df_final['Índice Deslizamento'] + df_final['Índice Inundação'])/2
def classificar(valor):
    if pd.isna(valor):
        return 'No data'
    if valor <= 0.19:
        return 'Very low'
    if valor <= 0.39:
        return 'Low'
    if valor <= 0.59:
        return 'Medium'
    if valor <= 0.79:
        return 'High'
    return 'Very high'

df_final['Label Risco Médio'] = df_final['Índice Risco Médio'].apply(classificar)

df_final['Label Risco Médio'].value_counts()

Label Risco Médio
Medium       2116
Low          1755
High         1080
Very low      399
Very high     219
No data         1
Name: count, dtype: int64

In [54]:
df_final['Município'][df_final['Índice Risco Médio'].isna()]

1773    Fernando de Noronha/PE
Name: Município, dtype: str

In [57]:
emendas.head(5)

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
69583,202338950001,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,1,CORAÇÃO DE MARIA - BA,2908903,CORAÇÃO DE MARIA,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,1500000.0,"1500000,00","1500000,00","0,00","0,00","0,00"
69584,202338950002,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,2,CORIBE - BA,2909109,CORIBE,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,2000000.0,"2000000,00","2000000,00","0,00","0,00","0,00"
69585,202338950003,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,3,MÚLTIPLO,Sem informação,Múltiplo,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,8218164.0,"8218164,00","8218164,00","0,00","0,00","0,00"
69586,202338950004,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,4,ITATIM - BA,2916856,ITATIM,2900000,...,2E90,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,600000.0,"600000,00","600000,00","0,00","0,00","0,00"
69587,202338950005,2023,Emenda Individual - Transferências com Finalid...,3895,ABILIO SANTANA,5,SANTA TERESINHA - BA,2928505,SANTA TERESINHA,2900000,...,2E89,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,0000,INCREMENTO TEMPORARIO AO CUSTEIO DOS SERVICOS ...,1500000.0,"1500000,00","1500000,00","0,00","0,00","0,00"

In [64]:
#How much money, how many towns
total = emendas['Valor Empenhado'].sum()
print ("earmarks total")
print (total)

earmarks total
164216823212.27002

In [65]:
municipal = emendas[emendas['Código Município IBGE'] != 'Sem informação']['Valor Empenhado'].sum()
print ("municipal earmarks total")
print(municipal)

municipal earmarks total
8834206204.919998

In [66]:
ambiental = df_final['Valor Empenhado'].sum()
print ("ambiental earmarks total")
print(ambiental)

ambiental earmarks total
54603178.18

In [68]:
print("Count of cities")
print({df_final['Valor Empenhado'].notna().sum()})

Count of cities
{np.int64(24)}

Waffle for the opening visual

In [69]:
%whos DataFrame

Variable            Type         Data/Info
------------------------------------------
ambientais          DataFrame    Shape: (269, 28)
ambiental_cidades   DataFrame    Shape: (25, 2)
deslizamento        DataFrame    Shape: (5570, 10)
df_final            DataFrame    Shape: (5570, 11)
emendas             DataFrame    Shape: (24493, 28)
inundacao           DataFrame    Shape: (5570, 10)
riscos              DataFrame    Shape: (5570, 19)
riskadapta          DataFrame    Shape: (558, 23)

In [71]:
#10000 dots
waffle = pd.DataFrame({
    'Category': ['National and state level','Municipal, other','Municipal, environmental'],
    'Dots': [10000 - round(municipal / total * 10000),round(municipal / total * 10000) - round(ambiental / total * 10000),round(ambiental / total * 10000)]
})
waffle

                   Category  Dots
0  National and state level  9462
1          Municipal, other   535
2  Municipal, environmental     3

## High or very high risk

In [75]:
df_final

,Código IBGE,Município,Índice Deslizamento,Cor Deslizamento,Label Deslizamento,Índice Inundação,Cor Inundação,Label Inundação,Valor Empenhado,Índice Risco Médio,Label Risco Médio
0,5200050,Abadia de Goiás/GO,0.12,#02C650,Muito baixo,0.19,#02C650,Muito baixo,NaN,0.155,Very low
1,3100104,Abadia dos Dourados/MG,0.54,#FFCD00,Médio,0.60,#FF8300,Alto,NaN,0.570,Medium
2,5200100,Abadiânia/GO,0.49,#FFCD00,Médio,0.47,#FFCD00,Médio,NaN,0.480,Medium
3,3100203,Abaeté/MG,0.40,#FFCD00,Médio,0.51,#FFCD00,Médio,NaN,0.455,Medium
4,1500107,Abaetetuba/PA,0.48,#FFCD00,Médio,0.78,#FF8300,Alto,NaN,0.630,High
...,...,...,...,...,...,...,...,...,...,...,...
5565,2933604,Xique-Xique/BA,0.60,#FF8300,Alto,0.72,#FF8300,Alto,NaN,0.660,High
5566,2517407,Zabelê/PB,0.57,#FFCD00,Médio,0.62,#FF8300,Alto,NaN,0.595,High
5567,3557154,Zacarias/SP,0.12,#02C650,Muito baixo,0.26,#A9DE00,Baixo,NaN,0.190,Very low
5568,2114007,Zé Doca/MA,0.61,#FF8300,Alto,0.83,#F40000,Muito alto,NaN,0.720,High
5569,4219853,Zortéa/SC,0.23,#A9DE00,Baixo,0.33,#A9DE00,Baixo,NaN,0.280,Low

In [72]:
%whos DataFrame

Variable            Type         Data/Info
------------------------------------------
ambientais          DataFrame    Shape: (269, 28)
ambiental_cidades   DataFrame    Shape: (25, 2)
deslizamento        DataFrame    Shape: (5570, 10)
df_final            DataFrame    Shape: (5570, 11)
emendas             DataFrame    Shape: (24493, 28)
inundacao           DataFrame    Shape: (5570, 10)
riscos              DataFrame    Shape: (5570, 19)
riskadapta          DataFrame    Shape: (558, 23)
waffle              DataFrame    Shape: (3, 2)

In [74]:
risco_alto = df_final[df_final['Label Risco Médio'].isin(['High', 'Very high'])]
len(risco_alto)

1299

In [75]:
risco_alto

,Código IBGE,Município,Índice Deslizamento,Cor Deslizamento,Label Deslizamento,Índice Inundação,Cor Inundação,Label Inundação,Valor Empenhado,Índice Risco Médio,Label Risco Médio
4,1500107,Abaetetuba/PA,0.48,#FFCD00,Médio,0.78,#FF8300,Alto,NaN,0.630,High
11,1500131,Abel Figueiredo/PA,0.54,#FFCD00,Médio,0.67,#FF8300,Alto,NaN,0.605,High
12,3100302,Abre Campo/MG,0.63,#FF8300,Alto,0.73,#FF8300,Alto,NaN,0.680,High
13,2600054,Abreu e Lima/PE,0.99,#F40000,Muito alto,0.93,#F40000,Muito alto,NaN,0.960,Very high
16,2100055,Açailândia/MA,0.66,#FF8300,Alto,0.67,#FF8300,Alto,NaN,0.665,High
...,...,...,...,...,...,...,...,...,...,...,...
5560,1200708,Xapuri/AC,0.57,#FFCD00,Médio,0.74,#FF8300,Alto,NaN,0.655,High
5563,2616506,Xexéu/PE,0.62,#FF8300,Alto,0.66,#FF8300,Alto,NaN,0.640,High
5565,2933604,Xique-Xique/BA,0.60,#FF8300,Alto,0.72,#FF8300,Alto,NaN,0.660,High
5566,2517407,Zabelê/PB,0.57,#FFCD00,Médio,0.62,#FF8300,Alto,NaN,0.595,High
5568,2114007,Zé Doca/MA,0.61,#FF8300,Alto,0.83,#F40000,Muito alto,NaN,0.720,High

## High risk, no money

In [76]:
risco_alto[risco_alto['Valor Empenhado'].isna()][['Município','Índice Risco Médio','Label Risco Médio']].sort_values('Índice Risco Médio', ascending=False).head(10)

                        Município  Índice Risco Médio Label Risco Médio
3787               Pilõezinhos/PB               1.000         Very high
2341                    Itambé/PE               1.000         Very high
62                  Água Preta/PE               1.000         Very high
40                        Afuá/PA               1.000         Very high
3943                    Portel/PA               0.990         Very high
4174                  Ribeirão/PE               0.985         Very high
1879                 Gameleira/PE               0.985         Very high
4375  Santa Cruz do Capibaribe/PE               0.980         Very high
1286                     Coari/AM               0.975         Very high
779                     Breves/PA               0.975         Very high

In [77]:
#max risk versus money 
df_final.nlargest(1, 'Índice Risco Médio')[['Município', 'Índice Risco Médio', 'Valor Empenhado']]

   Município  Índice Risco Médio  Valor Empenhado
40   Afuá/PA                 1.0              NaN

In [78]:
df_final[df_final['Índice Risco Médio'].eq(df_final['Índice Risco Médio'].max())][['Município', 'Índice Risco Médio', 'Valor Empenhado']]

           Município  Índice Risco Médio  Valor Empenhado
40           Afuá/PA                 1.0              NaN
62     Água Preta/PE                 1.0              NaN
2341       Itambé/PE                 1.0              NaN
3787  Pilõezinhos/PB                 1.0              NaN

DF FINAL  RISCO VERSUS EMENDAS

In [79]:
df_final.to_csv('data/risco_emendas.csv', index=False, sep=';', encoding='utf-8-sig', decimal=',')

## Reported disasters
I DOWNLOADED Atlas Digital de Desastres (atlasdigital.mdr.gov.br) records disaster reported by a municipality since 1991.

In [80]:
atlas = pd.read_excel('data/dados_brutos/Atlas_1991_2025_Consolidado.xlsx')
atlas.shape

(76191, 70)

In [82]:
atlas.columns.tolist()

['Protocolo_S2iD',
 'Nome_Municipio',
 'Sigla_UF',
 'regiao',
 'Data_Registro',
 'Data_Evento',
 'Cod_Cobrade',
 'tipologia',
 'descricao_tipologia',
 'grupo_de_desastre',
 'Cod_IBGE_Mun',
 'Setores Censitários',
 'Status',
 'DH_Descricao',
 'DH_MORTOS',
 'DH_FERIDOS',
 'DH_ENFERMOS',
 'DH_DESABRIGADOS',
 'DH_DESALOJADOS',
 'DH_DESAPARECIDOS',
 'DH_AFETADOS_SECA_ESTIAGEM',
 'DH_total_danos_humanos_diretos',
 'DH_OUTROS AFETADOS',
 'DM_Descricao',
 'DM_Uni Habita Danificadas',
 'DM_Uni Habita Destruidas',
 'DM_Uni Habita Valor',
 'DM_Inst Saúde Danificadas',
 'DM_Inst Saúde Destruidas',
 'DM_Inst Saúde Valor',
 'DM_Inst Ensino Danificadas',
 'DM_Inst Ensino Destruidas',
 'DM_Inst Ensino Valor',
 'DM_Inst Serviços Danificadas',
 'DM_Inst Serviços Destruidas',
 'DM_Inst Serviços Valor',
 'DM_Inst Comuni Danificadas',
 'DM_Inst Comuni Destruidas',
 'DM_Inst Comuni Valor',
 'DM_Obras de Infra Danificadas',
 'DM_Obras de Infra Destruidas',
 'DM_Obras de Infra Valor',
 'DM_total_danos_materiais',
 'DA_Descricao',
 'DA_Polui/cont da água',
 'DA_Polui/cont do ar',
 'DA_Polui/cont do solo',
 'DA_Dimi/exauri hídrico',
 "DA_Incêndi parques/APA's/APP's",
 'PEPL_Descricao',
 'PEPL_Assis_méd e emergên(R$)',
 'PEPL_Abast de água pot(R$)',
 'PEPL_sist de esgotos sanit(R$)',
 'PEPL_Sis limp e rec lixo (R$)',
 'PEPL_Sis cont pragas (R$)',
 'PEPL_distrib energia (R$)',
 'PEPL_Telecomunicações (R$)',
 'PEPL_Tran loc/reg/l_curso (R$)',
 'PEPL_Distrib combustíveis(R$)',
 'PEPL_Segurança pública (R$)',
 'PEPL_Ensino (R$)',
 'PEPL_total_publico',
 'PEPR_Descricao',
 'PEPR_Agricultura (R$)',
 'PEPR_Pecuária (R$)',
 'PEPR_Indústria (R$)',
 'PEPR_Comércio (R$)',
 'PEPR_Serviços (R$)',
 'PEPR_total_privado',
 'PE_PLePR']

In [83]:
atlas['descricao_tipologia'].unique()

<ArrowStringArray>
[                'Estiagem e Seca',                      'Enxurradas',
            'Vendavais e Ciclones',                      'Inundações',
                         'Granizo',             'Doenças infecciosas',
                         'Tornado',                          'Erosão',
                     'Alagamentos',              'Movimento de Massa',
                          'Outros',              'Incêndio Florestal',
                 'Chuvas Intensas',                    'Onda de Frio',
 'Rompimento/Colapso de barragens',   'Onda de Calor e Baixa Umidade']
Length: 16, dtype: str

Geo-hydrological: enxurrada, inundacoes, alagamentos, movimentos de massa, chuvas intensas. Year: Data Evento

In [85]:
tipos = ['Enxurradas', 'Inundações', 'Alagamentos', 'Movimento de Massa', 'Chuvas Intensas']
desastres = atlas[atlas['descricao_tipologia'].isin(tipos)].copy()
desastres['Ano_Evento'] = pd.to_datetime(desastres['Data_Evento']).dt.year
desastres.head()

Task was destroyed but it is pending!
task: <Task pending name='Task-431' coro=<_async_in_context.<locals>.run_in_context() done, defined at /Users/gqueiroz/.venvs/lede/lib/python3.13/site-packages/ipykernel/utils.py:57> wait_for=<Task pending name='Task-432' coro=<Kernel.shell_main() running at /Users/gqueiroz/.venvs/lede/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at /Users/gqueiroz/.venvs/lede/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py:563]>
/Users/gqueiroz/.venvs/lede/lib/python3.13/site-packages/pandas/core/internals/blocks.py:650: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  return type(self)(values, placement=self._mgr_locs, ndim=self.ndim, refs=refs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-432' coro=<Kernel.shell_main() running at /Users/gqueiroz/.venvs/lede/lib/python3.13/site-packages/ipykernel/kernelbase.py:597> cb=[Task.task_wakeup()]>

,Protocolo_S2iD,Nome_Municipio,Sigla_UF,regiao,Data_Registro,Data_Evento,Cod_Cobrade,tipologia,descricao_tipologia,grupo_de_desastre,...,PEPL_total_publico,PEPR_Descricao,PEPR_Agricultura (R$),PEPR_Pecuária (R$),PEPR_Indústria (R$),PEPR_Comércio (R$),PEPR_Serviços (R$),PEPR_total_privado,PE_PLePR,Ano_Evento
8,AC-P-1200401-12200-19910121,Rio Branco,AC,Norte,1991-01-21,1991-01-21,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
26,RJ-P-3305802-12200-19910130,Teresópolis,RJ,Sudeste,1991-01-30,1991-01-30,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
30,ES-P-3201209-12100-19910214,Cachoeiro de Itapemirim,ES,Sudeste,1991-02-14,1991-02-14,12100,7,Inundações,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
57,PR-R-4125902-12200-19910221,São Pedro do Paraná,PR,Sul,1991-02-21,1991-02-21,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
65,MT-J-5107859-12200-19910226,São Félix do Araguaia,MT,Centro-oeste,1991-02-26,1991-02-26,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991

In [86]:
desastres.shape

(29353, 71)

Totals since 1991, deaths and material damage

In [87]:
desastres['DH_MORTOS'].sum(), desastres['DM_total_danos_materiais'].sum()

(np.int64(4612), np.float64(84066580755.98))

Deaths per year

In [88]:
mortos = desastres.groupby('Ano_Evento')['DH_MORTOS'].sum().reset_index()
mortos.head()

   Ano_Evento  DH_MORTOS
0        1991         36
1        1992         11
2        1993         16
3        1994          4
4        1995         31

In [89]:
mortos

    Ano_Evento  DH_MORTOS
0         1991         36
1         1992         11
2         1993         16
3         1994          4
4         1995         31
5         1996         12
6         1997          8
7         1998          7
8         1999          7
9         2000         53
10        2001         65
11        2002         86
12        2003         91
13        2004        190
14        2005        107
15        2006        143
16        2007        114
17        2008        196
18        2009        262
19        2010        339
20        2011        947
21        2012         82
22        2013        132
23        2014         63
24        2015         47
25        2016         56
26        2017         48
27        2018         50
28        2019         89
29        2020        165
30        2021         58
31        2022        600
32        2023        171
33        2024        263
34        2025         63

In [ ]:
DESASTRES E MORTOS CSV

In [90]:
desastres.to_csv('data/desastres.csv', index=False, sep=';', encoding='utf-8-sig', decimal=',')
mortos.to_csv('data/mortos.csv', index=False)

## Events and deaths since 2023

In [91]:
desastres

,Protocolo_S2iD,Nome_Municipio,Sigla_UF,regiao,Data_Registro,Data_Evento,Cod_Cobrade,tipologia,descricao_tipologia,grupo_de_desastre,...,PEPL_total_publico,PEPR_Descricao,PEPR_Agricultura (R$),PEPR_Pecuária (R$),PEPR_Indústria (R$),PEPR_Comércio (R$),PEPR_Serviços (R$),PEPR_total_privado,PE_PLePR,Ano_Evento
8,AC-P-1200401-12200-19910121,Rio Branco,AC,Norte,1991-01-21,1991-01-21,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
26,RJ-P-3305802-12200-19910130,Teresópolis,RJ,Sudeste,1991-01-30,1991-01-30,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
30,ES-P-3201209-12100-19910214,Cachoeiro de Itapemirim,ES,Sudeste,1991-02-14,1991-02-14,12100,7,Inundações,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
57,PR-R-4125902-12200-19910221,São Pedro do Paraná,PR,Sul,1991-02-21,1991-02-21,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
65,MT-J-5107859-12200-19910226,São Félix do Araguaia,MT,Centro-oeste,1991-02-26,1991-02-26,12200,2,Enxurradas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76186,SC-F-4212106-13214-20251231,Palmitos,SC,Sul,2026-01-02,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,90000.0,As chuvas intensas e o elevado escoamento supe...,100000.0,80000.0,0.0,0.0,90000.0,270000.0,360000.0,2025
76187,MG-F-3147907-13214-20251231,Passos,MG,Sudeste,2026-01-06,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,620000.0,As intensas chuvas inviabilizaram as estradas ...,10000.0,10000.0,0.0,0.0,0.0,20000.0,640000.0,2025
76188,SC-F-4212304-13214-20251231,Paulo Lopes,SC,Sul,2026-01-07,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025
76189,SC-F-4216305-13214-20251231,São João Batista,SC,Sul,2026-01-01,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,350000.0,Com efeito do desastre ocasionou a interrupção...,100000.0,0.0,0.0,0.0,0.0,100000.0,450000.0,2025
76190,SC-F-4219606-13214-20251231,Xavantina,SC,Sul,2026-01-19,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,2500000.0,Não houve prejuizos privados.,0.0,0.0,0.0,0.0,0.0,0.0,2500000.0,2025

In [92]:
recentes = desastres[desastres['Ano_Evento'] >= 2023]

recentes['DH_MORTOS'].sum()

np.int64(497)

In [93]:
eventos_municipio = recentes.groupby('Cod_IBGE_Mun').agg(Nome_Municipio=('Nome_Municipio', 'first'), Sigla_UF=('Sigla_UF', 'first'), Eventos=('Nome_Municipio', 'size')).reset_index()
eventos_municipio.sort_values('Eventos', ascending=False).head(10)

      Cod_IBGE_Mun  Nome_Municipio Sigla_UF  Eventos
465        2607208         Ipojuca       PE       47
873        3136702    Juiz de Fora       MG       27
1578       4210100           Mafra       SC       24
2226       5005806         Nioaque       MS       23
149        1505304       Oriximiná       PA       21
376        2313807     Uruburetama       CE       17
446        2600054    Abreu e Lima       PE       16
1474       4202438  Bocaina do Sul       SC       16
2204       5002704    Campo Grande       MS       16
1483       4202909         Brusque       SC       15

Ipojuca

In [94]:
recentes[recentes['Cod_IBGE_Mun'].astype(str) == '2607208']['descricao_tipologia'].value_counts()

descricao_tipologia
Movimento de Massa    43
Chuvas Intensas        2
Alagamentos            2
Name: count, dtype: int64

## Events x environmental money

In [96]:
eventos_emendas = eventos_municipio.merge(ambiental_cidades, left_on='Cod_IBGE_Mun', right_on='Código Município IBGE', how='left')
eventos_emendas['Valor Empenhado'] = eventos_emendas['Valor Empenhado'].fillna(0)
eventos_emendas.sort_values('Eventos', ascending=False).head(10)

ValueError: You are trying to merge on int64 and str columns for key 'Cod_IBGE_Mun'. If you wish to proceed you should use pd.concat

In [97]:
eventos_emendas = eventos_municipio.merge(
    ambiental_cidades,
    left_on=eventos_municipio['Cod_IBGE_Mun'].astype(str),
    right_on=ambiental_cidades['Código Município IBGE'].astype(str),
    how='left')
eventos_emendas['Valor Empenhado'] = eventos_emendas['Valor Empenhado'].fillna(0)
eventos_emendas.sort_values('Eventos', ascending=False).head(10)

,key_0,Cod_IBGE_Mun,Nome_Municipio,Sigla_UF,Eventos,Código Município IBGE,Valor Empenhado
465,2607208,2607208,Ipojuca,PE,47,NaN,0.0
873,3136702,3136702,Juiz de Fora,MG,27,NaN,0.0
1578,4210100,4210100,Mafra,SC,24,NaN,0.0
2226,5005806,5005806,Nioaque,MS,23,NaN,0.0
149,1505304,1505304,Oriximiná,PA,21,NaN,0.0
376,2313807,2313807,Uruburetama,CE,17,NaN,0.0
446,2600054,2600054,Abreu e Lima,PE,16,NaN,0.0
1474,4202438,4202438,Bocaina do Sul,SC,16,NaN,0.0
2204,5002704,5002704,Campo Grande,MS,16,NaN,0.0
1483,4202909,4202909,Brusque,SC,15,4202909,340000.0

Who had events and also got money?

In [98]:
eventos_emendas[eventos_emendas['Valor Empenhado'] > 0].sort_values('Eventos', ascending=False)

,key_0,Cod_IBGE_Mun,Nome_Municipio,Sigla_UF,Eventos,Código Município IBGE,Valor Empenhado
1483,4202909,4202909,Brusque,SC,15,4202909,340000.00
1787,4304606,4304606,Canoas,RS,7,4304606,200000.00
1863,4307708,4307708,Esteio,RS,5,4307708,150000.00
1864,4307807,4307807,Estrela,RS,4,4307807,200000.00
1176,3303906,3303906,Petrópolis,RJ,4,3303906,1863800.00
412,2408102,2408102,Natal,RN,4,2408102,5750000.00
1520,4205555,4205555,Frei Rogério,SC,3,4205555,382000.00
1197,3305802,3305802,Teresópolis,RJ,3,3305802,1000000.00
1187,3304904,3304904,São Gonçalo,RJ,2,3304904,12219069.00
2251,5103403,5103403,Cuiabá,MT,2,5103403,2000000.00
2281,5108402,5108402,Várzea Grande,MT,2,5108402,14000000.00
1182,3304557,3304557,Rio de Janeiro,RJ,2,3304557,4116150.00
1150,3301009,3301009,Campos dos Goytacazes,RJ,2,3301009,1268737.18
470,2607901,2607901,Jaboatão dos Guararapes,PE,2,2607901,5000000.00
469,2607752,2607752,Itapissuma,PE,1,2607752,500000.00
439,2504009,2504009,Campina Grande,PB,1,2504009,500000.00
342,2304400,2304400,Fortaleza,CE,1,2304400,250000.00

## Deaths since 2023 x money

In [99]:
%whos DataFrame

Variable            Type         Data/Info
------------------------------------------
ambientais          DataFrame    Shape: (269, 28)
ambiental_cidades   DataFrame    Shape: (25, 2)
atlas               DataFrame    Shape: (76191, 70)
desastres           DataFrame    Shape: (29353, 71)
deslizamento        DataFrame    Shape: (5570, 10)
df_final            DataFrame    Shape: (5570, 11)
emendas             DataFrame    Shape: (24493, 28)
eventos_emendas     DataFrame    Shape: (2317, 7)
eventos_municipio   DataFrame    Shape: (2317, 4)
inundacao           DataFrame    Shape: (5570, 10)
mortos              DataFrame    Shape: (35, 2)
recentes            DataFrame    Shape: (5779, 71)
risco_alto          DataFrame    Shape: (1299, 11)
riscos              DataFrame    Shape: (5570, 19)
riskadapta          DataFrame    Shape: (558, 23)
waffle              DataFrame    Shape: (3, 2)

In [100]:
recentes

,Protocolo_S2iD,Nome_Municipio,Sigla_UF,regiao,Data_Registro,Data_Evento,Cod_Cobrade,tipologia,descricao_tipologia,grupo_de_desastre,...,PEPL_total_publico,PEPR_Descricao,PEPR_Agricultura (R$),PEPR_Pecuária (R$),PEPR_Indústria (R$),PEPR_Comércio (R$),PEPR_Serviços (R$),PEPR_total_privado,PE_PLePR,Ano_Evento
62115,BA-F-2907806-13214-20230101,Cícero Dantas,BA,Nordeste,2023-01-03 15:14:21,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,52000.0,ATÉ O MOMENTO NÃO AVALIADO DEVIDO A PRECARIEDA...,0.0,0.0,0.0,0.0,0.0,0.0,52000.0,2023
62116,MG-F-3153400-13214-20230101,Presidente Olegário,MG,Sudeste,2023-01-18 17:06:06,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,150000.0,PREJUÍZOS NA AGRICULTURA SENDO ESTA A FRUTICUL...,100000.0,2000000.0,0.0,0.0,0.0,2100000.0,2250000.0,2023
62117,MG-F-3130903-13214-20230101,Inhapim,MG,Sudeste,2023-01-19 11:02:49,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,700000.0,COM QUEDAS DE ESTRAS E PONTES IMPOSSIBILITOU Q...,600000.0,450000.0,0.0,0.0,0.0,1050000.0,1750000.0,2023
62118,MG-F-3128402-13214-20230101,Guarani,MG,Sudeste,2023-01-05 11:25:07,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,0.0,Devido às chuvas intensas ocorridas no municíp...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023
62119,MG-F-3155801-13214-20230101,Rio Pomba,MG,Sudeste,2023-01-05 13:28:49,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,2000.0,Devido às chuvas intensas ocorridas no municíp...,0.0,0.0,0.0,0.0,0.0,0.0,2000.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76186,SC-F-4212106-13214-20251231,Palmitos,SC,Sul,2026-01-02 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,90000.0,As chuvas intensas e o elevado escoamento supe...,100000.0,80000.0,0.0,0.0,90000.0,270000.0,360000.0,2025
76187,MG-F-3147907-13214-20251231,Passos,MG,Sudeste,2026-01-06 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,620000.0,As intensas chuvas inviabilizaram as estradas ...,10000.0,10000.0,0.0,0.0,0.0,20000.0,640000.0,2025
76188,SC-F-4212304-13214-20251231,Paulo Lopes,SC,Sul,2026-01-07 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025
76189,SC-F-4216305-13214-20251231,São João Batista,SC,Sul,2026-01-01 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,350000.0,Com efeito do desastre ocasionou a interrupção...,100000.0,0.0,0.0,0.0,0.0,100000.0,450000.0,2025
76190,SC-F-4219606-13214-20251231,Xavantina,SC,Sul,2026-01-19 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,2500000.0,Não houve prejuizos privados.,0.0,0.0,0.0,0.0,0.0,0.0,2500000.0,2025

In [101]:
mortos = recentes.groupby('Cod_IBGE_Mun', as_index=False).agg(Nome_Municipio=('Nome_Municipio', 'first'), Sigla_UF=('Sigla_UF', 'first'), DH_MORTOS=('DH_MORTOS', 'sum'))
mortos.head()

   Cod_IBGE_Mun         Nome_Municipio Sigla_UF  DH_MORTOS
0       1100015  Alta Floresta D`Oeste       RO          0
1       1100023              Ariquemes       RO          0
2       1100049                 Cacoal       RO          0
3       1100056             Cerejeiras       RO          0
4       1100114                   Jaru       RO          0

In [102]:
mortos['Cod_IBGE_Mun'] = mortos['Cod_IBGE_Mun'].astype(str)

In [103]:
mortos = mortos.merge(ambiental_cidades, left_on='Cod_IBGE_Mun', right_on='Código Município IBGE', how='left')
mortos['Valor Empenhado'] = mortos['Valor Empenhado'].fillna(0)
mortos.sort_values('DH_MORTOS', ascending=False).head(10)

,Cod_IBGE_Mun,Nome_Municipio,Sigla_UF,DH_MORTOS,Código Município IBGE,Valor Empenhado
1301,3550704,São Sebastião,SP,56,NaN,0.0
1787,4304606,Canoas,RS,31,4304606,200000.0
1124,3203403,Mimoso do Sul,ES,18,NaN,0.0
1833,4306205,Cruzeiro do Sul,RS,17,NaN,0.0
1969,4312609,Muçum,RS,14,NaN,0.0
2049,4315800,Roca Sales,RS,14,NaN,0.0
1752,4302105,Bento Gonçalves,RS,11,NaN,0.0
2099,4318705,São Leopoldo,RS,11,NaN,0.0
844,3131307,Ipatinga,MG,10,NaN,0.0
1802,4305108,Caxias do Sul,RS,9,NaN,0.0

In [105]:
#city with death and no money 
mortos[mortos['DH_MORTOS'] > 0]['Valor Empenhado'].eq(0).value_counts()

Valor Empenhado
True     165
False      7
Name: count, dtype: int64

In [ ]:
CSV EVENTOS X EMENDAS SALVO

In [106]:
eventos_emendas.to_csv('data/eventos_emendas.csv', index=False, sep=';', encoding='utf-8-sig', decimal=',')

In [107]:
eventos_emendas

,key_0,Cod_IBGE_Mun,Nome_Municipio,Sigla_UF,Eventos,Código Município IBGE,Valor Empenhado
0,1100015,1100015,Alta Floresta D`Oeste,RO,1,NaN,0.0
1,1100023,1100023,Ariquemes,RO,1,NaN,0.0
2,1100049,1100049,Cacoal,RO,2,NaN,0.0
3,1100056,1100056,Cerejeiras,RO,1,NaN,0.0
4,1100114,1100114,Jaru,RO,4,NaN,0.0
...,...,...,...,...,...,...,...
2312,5220686,5220686,Simolândia,GO,1,NaN,0.0
2313,5221577,5221577,Uirapuru,GO,2,NaN,0.0
2314,5221700,5221700,Uruana,GO,1,NaN,0.0
2315,5221858,5221858,Valparaíso de Goiás,GO,1,NaN,0.0
2316,5300108,5300108,Brasília,DF,1,NaN,0.0

In [108]:
##scatter Flourish
scatter = eventos_emendas.copy()
scatter['name'] = scatter['Nome_Municipio'] + '/' + scatter['Sigla_UF']
scatter['Grupo'] = (scatter['Valor Empenhado'] > 0).map({True: 'Received', False: 'No earmark'})

scatter = scatter[['name', 'Eventos', 'Valor Empenhado', 'Grupo']]
scatter.to_csv('data/scatter_eventos_valor.csv', index=False)

len(scatter), (scatter['Grupo'] == 'Received').sum()

(2317, np.int64(17))

## Money follow risk?

In [109]:
%whos DataFrame

Variable            Type         Data/Info
------------------------------------------
ambientais          DataFrame    Shape: (269, 28)
ambiental_cidades   DataFrame    Shape: (25, 2)
atlas               DataFrame    Shape: (76191, 70)
desastres           DataFrame    Shape: (29353, 71)
deslizamento        DataFrame    Shape: (5570, 10)
df_final            DataFrame    Shape: (5570, 11)
emendas             DataFrame    Shape: (24493, 28)
eventos_emendas     DataFrame    Shape: (2317, 7)
eventos_municipio   DataFrame    Shape: (2317, 4)
inundacao           DataFrame    Shape: (5570, 10)
mortos              DataFrame    Shape: (2317, 6)
recentes            DataFrame    Shape: (5779, 71)
risco_alto          DataFrame    Shape: (1299, 11)
riscos              DataFrame    Shape: (5570, 19)
riskadapta          DataFrame    Shape: (558, 23)
scatter             DataFrame    Shape: (2317, 4)
waffle              DataFrame    Shape: (3, 2)

In [114]:
df_final['Código IBGE'] = df_final['Código IBGE'].astype(str)
eventos_municipio['Cod_IBGE_Mun'] = eventos_municipio['Cod_IBGE_Mun'].astype(str)

In [115]:
correlacao = df_final.merge(eventos_municipio[['Cod_IBGE_Mun', 'Eventos']], left_on='Código IBGE', right_on='Cod_IBGE_Mun', how='left')
correlacao = correlacao[['Valor Empenhado', 'Índice Deslizamento', 'Índice Inundação', 'Índice Risco Médio', 'Eventos']]
correlacao = correlacao.fillna(0)
matriz = correlacao.corr(method='spearman').round(2)
matriz.style.background_gradient(cmap='RdBu_r', vmin=-1, vmax=1)

CSV correlacao

In [116]:
matriz.to_csv('data/matriz_correlacao.csv', sep=';', encoding='utf-8-sig', decimal=',')

## extra analysis

In [118]:
ambientais

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
69799,202327760019,2023,Emenda Individual - Transferências com Finalid...,2776,ALESSANDRO MOLON,19,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,20WM,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",0000,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",488667.88,"0,00","0,00","12805,02","0,00","475862,86"
69899,202330420002,2023,Emenda Individual - Transferências com Finalid...,3042,ALTINEU CORTES,2,SÃO GONÇALO - RJ,3304904,SÃO GONÇALO,3300000,...,00SY,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",0000,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",12219069.00,"518333,00","518333,00","11700736,00","0,00","0,00"
69942,202310740007,2023,Emenda Individual - Transferências com Finalid...,1074,ANDRE DE PAULA,7,ITAPISSUMA - PE,2607752,ITAPISSUMA,2600000,...,00T5,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",0000,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",500000.00,"0,00","0,00","143976,05","0,00","356023,95"
69959,202320830015,2023,Emenda Individual - Transferências com Finalid...,2083,ANDRE FIGUEIREDO,15,RUSSAS - CE,2311801,RUSSAS,2300000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,250000.00,"0,00","0,00","70400,00","0,00","179600,00"
70021,202339150004,2023,Emenda Individual - Transferências com Finalid...,3915,AROLDO MARTINS,4,PARANÁ (UF),Sem informação,Sem informação,4100000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,162920.00,"0,00","0,00","0,00","0,00","162920,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93683,202640700020,2026,Emenda Individual - Transferências com Finalid...,4070,TALIRIA PETRONE,20,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,21A9,"IMPLEMENTACAO DE PROGRAMAS, PLANOS E ACOES PAR...",0000,"IMPLEMENTACAO DE PROGRAMAS, PLANOS E ACOES PAR...",300000.00,"300000,00","300000,00","0,00","0,00","0,00"
93693,202644830017,2026,Emenda Individual - Transferências com Finalid...,4483,TARCISIO MOTTA,17,RIO DE JANEIRO - RJ,3304557,RIO DE JANEIRO,3300000,...,00VD,APOIO AO DESENVOLVIMENTO E IMPLEMENTACAO DE AC...,0000,APOIO AO DESENVOLVIMENTO E IMPLEMENTACAO DE AC...,600000.00,"0,00","0,00","0,00","0,00","0,00"
93805,202640880009,2026,Emenda Individual - Transferências com Finalid...,4088,VENEZIANO VITAL DO REGO,9,CAMPINA GRANDE - PB,2504009,CAMPINA GRANDE,2500000,...,00TB,"APOIO A IMPLANTACAO, AMPLIACAO OU MELHORIAS DE...",0000,"APOIO A IMPLANTACAO, AMPLIACAO OU MELHORIAS DE...",500000.00,"0,00","0,00","0,00","0,00","0,00"
93873,202637770008,2026,Emenda Individual - Transferências com Finalid...,3777,VITOR LIPPI,8,SÃO PAULO (UF),Sem informação,Sem informação,3500000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",2865000.00,"0,00","0,00","0,00","0,00","0,00"
93894,202638050005,2026,Emenda Individual - Transferências com Finalid...,3805,WELLINGTON FAGUNDES,5,CUIABÁ - MT,5103403,CUIABÁ,5100000,...,8172,COORDENACAO E FORTALECIMENTO DO SISTEMA NACION...,0000,COORDENACAO E FORTALECIMENTO DO SISTEMA NACION...,2000000.00,"0,00","0,00","0,00","0,00","0,00"

In [119]:
#authors
ambientais.groupby('Nome do Autor da Emenda')['Valor Empenhado'].sum().sort_values(ascending=False).head(30)

Nome do Autor da Emenda
BANCADA DE TOCANTINS                               71762750.00
BANCADA DE SANTA CATARINA                          48358320.00
BRUNO GANEM                                        39461990.69
MARCELO QUEIROZ                                    38922799.44
BANCADA DO MATO GROSSO DO SUL                      30000000.00
BANCADA DE SERGIPE                                 27680777.00
BANCADA DO RIO GRANDE DO NORTE                     24492366.00
DELEGADO MATHEUS LAIOLA                            23567695.12
DELEGADO BRUNO LIMA                                22154713.86
BANCADA DE PERNAMBUCO                              19600000.00
BANCADA DO MATO GROSSO                             14000000.00
ALTINEU CORTES                                     12419069.00
BANCADA DO AMAPA                                   10000000.00
COM. MISTA PERMANENTE SOBRE MUDANCAS CLIMATICAS     8975173.00
DR. FERNANDO MAXIMO                                 8862596.66
FRED COSTA                                          7499984.20
KIKO CELEGUIM                                       6241800.00
LUIZIANNE LINS                                      5597993.00
TALIRIA PETRONE                                     5229208.00
VENEZIANO VITAL DO REGO                             5000000.00
GLAUBER BRAGA                                       4761746.18
BANCADA DA BAHIA                                    4700000.00
CELIA XAKRIABA                                      4396090.00
FERNANDA MELCHIONNA                                 4048507.02
ERIKA HILTON                                        3985999.67
VITOR LIPPI                                         3864996.00
BANCADA DO PIAUI                                    3820000.00
ANA PAULA LIMA                                      3605000.00
CELIO STUDART                                       3532854.46
TABATA AMARAL                                       3220794.00
Name: Valor Empenhado, dtype: float64

In [120]:
ambientais

,Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,...,Código Ação,Nome Ação,Código Plano Orçamentário,Nome Plano Orçamentário,Valor Empenhado,Valor Liquidado,Valor Pago,Valor Restos A Pagar Inscritos,Valor Restos A Pagar Cancelados,Valor Restos A Pagar Pagos
69799,202327760019,2023,Emenda Individual - Transferências com Finalid...,2776,ALESSANDRO MOLON,19,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,20WM,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",0000,"APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UN...",488667.88,"0,00","0,00","12805,02","0,00","475862,86"
69899,202330420002,2023,Emenda Individual - Transferências com Finalid...,3042,ALTINEU CORTES,2,SÃO GONÇALO - RJ,3304904,SÃO GONÇALO,3300000,...,00SY,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",0000,"APOIO A PROJETOS E OBRAS DE REABILITACAO, DE A...",12219069.00,"518333,00","518333,00","11700736,00","0,00","0,00"
69942,202310740007,2023,Emenda Individual - Transferências com Finalid...,1074,ANDRE DE PAULA,7,ITAPISSUMA - PE,2607752,ITAPISSUMA,2600000,...,00T5,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",0000,"APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRA...",500000.00,"0,00","0,00","143976,05","0,00","356023,95"
69959,202320830015,2023,Emenda Individual - Transferências com Finalid...,2083,ANDRE FIGUEIREDO,15,RUSSAS - CE,2311801,RUSSAS,2300000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,250000.00,"0,00","0,00","70400,00","0,00","179600,00"
70021,202339150004,2023,Emenda Individual - Transferências com Finalid...,3915,AROLDO MARTINS,4,PARANÁ (UF),Sem informação,Sem informação,4100000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,APOIO A FORMULACAO E IMPLEMENTACAO DE POLITICA...,162920.00,"0,00","0,00","0,00","0,00","162920,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93683,202640700020,2026,Emenda Individual - Transferências com Finalid...,4070,TALIRIA PETRONE,20,RIO DE JANEIRO (UF),Sem informação,Sem informação,3300000,...,21A9,"IMPLEMENTACAO DE PROGRAMAS, PLANOS E ACOES PAR...",0000,"IMPLEMENTACAO DE PROGRAMAS, PLANOS E ACOES PAR...",300000.00,"300000,00","300000,00","0,00","0,00","0,00"
93693,202644830017,2026,Emenda Individual - Transferências com Finalid...,4483,TARCISIO MOTTA,17,RIO DE JANEIRO - RJ,3304557,RIO DE JANEIRO,3300000,...,00VD,APOIO AO DESENVOLVIMENTO E IMPLEMENTACAO DE AC...,0000,APOIO AO DESENVOLVIMENTO E IMPLEMENTACAO DE AC...,600000.00,"0,00","0,00","0,00","0,00","0,00"
93805,202640880009,2026,Emenda Individual - Transferências com Finalid...,4088,VENEZIANO VITAL DO REGO,9,CAMPINA GRANDE - PB,2504009,CAMPINA GRANDE,2500000,...,00TB,"APOIO A IMPLANTACAO, AMPLIACAO OU MELHORIAS DE...",0000,"APOIO A IMPLANTACAO, AMPLIACAO OU MELHORIAS DE...",500000.00,"0,00","0,00","0,00","0,00","0,00"
93873,202637770008,2026,Emenda Individual - Transferências com Finalid...,3777,VITOR LIPPI,8,SÃO PAULO (UF),Sem informação,Sem informação,3500000,...,2E87,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",0000,"IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, ...",2865000.00,"0,00","0,00","0,00","0,00","0,00"
93894,202638050005,2026,Emenda Individual - Transferências com Finalid...,3805,WELLINGTON FAGUNDES,5,CUIABÁ - MT,5103403,CUIABÁ,5100000,...,8172,COORDENACAO E FORTALECIMENTO DO SISTEMA NACION...,0000,COORDENACAO E FORTALECIMENTO DO SISTEMA NACION...,2000000.00,"0,00","0,00","0,00","0,00","0,00"

In [121]:
ambientais.groupby(['Nome do Autor da Emenda', 'Localidade de aplicação do recurso'])['Valor Empenhado'].sum().sort_values(ascending=False).head(25)

Nome do Autor da Emenda                          Localidade de aplicação do recurso
BANCADA DE TOCANTINS                             MÚLTIPLO                              71762750.00
BANCADA DE SANTA CATARINA                        MÚLTIPLO                              48358320.00
BRUNO GANEM                                      SÃO PAULO (UF)                        39461990.69
MARCELO QUEIROZ                                  Nacional                              38922799.44
BANCADA DO MATO GROSSO DO SUL                    MÚLTIPLO                              30000000.00
BANCADA DE SERGIPE                               MÚLTIPLO                              27680777.00
DELEGADO MATHEUS LAIOLA                          PARANÁ (UF)                           23567695.12
DELEGADO BRUNO LIMA                              SÃO PAULO (UF)                        22154713.86
BANCADA DO RIO GRANDE DO NORTE                   RIO GRANDE DO NORTE (UF)              18992366.00
BANCADA DE PERNAMBUCO                            PERNAMBUCO (UF)                       14600000.00
BANCADA DO MATO GROSSO                           VÁRZEA GRANDE - MT                    14000000.00
ALTINEU CORTES                                   SÃO GONÇALO - RJ                      12219069.00
BANCADA DO AMAPA                                 AMAPÁ (UF)                            10000000.00
COM. MISTA PERMANENTE SOBRE MUDANCAS CLIMATICAS  Nacional                               8975173.00
DR. FERNANDO MAXIMO                              RONDÔNIA (UF)                          5865000.00
LUIZIANNE LINS                                   CEARÁ (UF)                             5597993.00
BANCADA DO RIO GRANDE DO NORTE                   NATAL - RN                             5500000.00
BANCADA DE PERNAMBUCO                            JABOATÃO DOS GUARARAPES - PE           5000000.00
VENEZIANO VITAL DO REGO                          PARAÍBA (UF)                           4500000.00
FRED COSTA                                       MÚLTIPLO                               4499984.20
TALIRIA PETRONE                                  RIO DE JANEIRO (UF)                    4429208.00
VITOR LIPPI                                      SÃO PAULO (UF)                         3864996.00
BANCADA DO PIAUI                                 PIAUÍ (UF)                             3820000.00
BANCADA DA BAHIA                                 BAHIA (UF)                             3700000.00
CELIO STUDART                                    CEARÁ (UF)                             3532854.46
Name: Valor Empenhado, dtype: float64

In [122]:
#main earmarks
ambientais.groupby('Nome Ação')['Valor Empenhado'].agg(['count', 'sum']).sort_values('sum', ascending=False).head(30)

                                                    count           sum
Nome Ação
IMPLEMENTACAO DA AGENDA NACIONAL DE PROTECAO, D...     72  1.830121e+08
APOIO A PROJETOS E OBRAS DE REABILITACAO, DE AC...     19  1.361576e+08
APOIO A REALIZACAO DE ESTUDOS, PROJETOS E OBRAS...      6  5.801278e+07
APOIO A SISTEMAS DE DRENAGEM URBANA SUSTENTAVEL...      1  3.000000e+07
IMPLEMENTACAO DE ACOES DE CIDADANIA E EDUCACAO ...     37  2.294273e+07
IMPLEMENTACAO DE PROGRAMAS, PLANOS E ACOES PARA...     29  1.996795e+07
APOIO A CONSTRUCAO DA BARRAGEM OITICICA                 1  1.899237e+07
APOIO A REGULARIZACAO FUNDIARIA URBANA                  5  1.780000e+07
APOIO AO DESENVOLVIMENTO E IMPLEMENTACAO DE ACO...     15  1.535596e+07
APOIO A IMPLANTACAO DA ADUTORA DO AGRESTE               1  1.460000e+07
APOIO A IMPLANTACAO, AMPLIACAO OU MELHORIAS DE ...      8  1.250200e+07
FISCALIZACAO AMBIENTAL E PREVENCAO E COMBATE A ...      3  1.034462e+07
COORDENACAO E FORTALECIMENTO DO SISTEMA NACIONA...      8  8.993546e+06
APOIO A CRIACAO, GESTAO E IMPLEMENTACAO DAS UNI...     12  3.890216e+06
IMPLEMENTACAO DE POLITICAS PARA BIODIVERSIDADE,...      7  3.415000e+06
APOIO A PLANOS, PROJETOS E OBRAS DE REDUCAO DE ...      4  3.400000e+06
GESTAO TERRITORIAL E SOCIOAMBIENTAL DE PAISAGEN...      4  3.398511e+06
CONSERVACAO E RECUPERACAO DE BACIAS HIDROGRAFICAS       3  2.650000e+06
APOIO A IMPLANTACAO, AMPLIACAO, MELHORIAS OU AD...      3  2.648100e+06
PREVENCAO E CONTROLE DE INCENDIOS FLORESTAIS NA...      5  2.520961e+06
APOIO AO PLANEJAMENTO E A GESTAO URBANA MUNICIP...      1  1.629209e+06
ACOES DE PROTECAO E DEFESA CIVIL                        4  1.600000e+06
IMPLEMENTACAO E MONITORAMENTO DA POLITICA NACIO...      3  1.400000e+06
CONSTRUCAO DE SISTEMA INTEGRADO DE ABASTECIMENT...      1  1.200000e+06
GESTAO DO USO SUSTENTAVEL DA BIODIVERSIDADE E R...      3  1.199994e+06
ENFRENTAMENTO DOS PROCESSOS DE DESERTIFICACAO, ...      3  1.000000e+06
MONITORAMENTO AMBIENTAL E GESTAO DA INFORMACAO ...      2  9.070000e+05
APOIO A MELHORIA HABITACIONAL                           1  7.000000e+05
IMPLEMENTACAO DA POLITICA NACIONAL DE RECURSOS ...      2  6.993485e+05
FOMENTO A PROJETOS DE DESENVOLVIMENTO SUSTENTAV...      1  5.000000e+05

## Environmental money by state and region

In [123]:
ambientais.groupby('UF')['Valor Empenhado'].agg(['count', 'sum']).sort_values('sum', ascending=False)

                     count          sum
UF
SÃO PAULO               51  93258966.51
TOCANTINS                6  72762750.00
Sem informação          31  71149463.09
SANTA CATARINA           9  54084785.00
RIO DE JANEIRO          36  40472528.09
MATO GROSSO DO SUL       6  33629000.00
SERGIPE                  3  28980777.00
PERNAMBUCO              13  26549452.00
RIO GRANDE DO NORTE      6  25800694.00
PARANÁ                   7  25030615.12
MINAS GERAIS            22  21302054.79
MATO GROSSO              3  16300000.00
CEARÁ                   11  11805056.46
AMAPÁ                    1  10000000.00
RIO GRANDE DO SUL       15   9845217.68
GOIÁS                   11   7904743.11
BAHIA                    8   7788821.26
RONDÔNIA                 2   5865000.00
PARAÍBA                  4   5300000.00
ESPÍRITO SANTO           9   4198141.41
PIAUÍ                    3   4020000.00
AMAZONAS                 4   2991040.96
Múltiplo                 3   2212008.00
DISTRITO FEDERAL         4   1857616.00
ALAGOAS                  1    200000.00

In [124]:
ambientais.groupby('Região')['Valor Empenhado'].agg(['count', 'sum']).sort_values('sum', ascending=False)

              count           sum
Região
Sudeste         118  1.592317e+08
Nordeste         49  1.104448e+08
Norte            13  9.161879e+07
Sul              31  8.896062e+07
Nacional         31  7.114946e+07
Centro-Oeste     24  5.969136e+07
Múltiplo          3  2.212008e+06

In [125]:
#year to year
ambientais.groupby('Ano da Emenda')['Valor Empenhado'].agg(['count', 'sum'])

               count           sum
Ano da Emenda
2023              44  1.098463e+08
2024              88  1.762183e+08
2025              89  2.091665e+08
2026              48  8.807772e+07

## Events vs money by state

In [127]:
recentes

,Protocolo_S2iD,Nome_Municipio,Sigla_UF,regiao,Data_Registro,Data_Evento,Cod_Cobrade,tipologia,descricao_tipologia,grupo_de_desastre,...,PEPL_total_publico,PEPR_Descricao,PEPR_Agricultura (R$),PEPR_Pecuária (R$),PEPR_Indústria (R$),PEPR_Comércio (R$),PEPR_Serviços (R$),PEPR_total_privado,PE_PLePR,Ano_Evento
62115,BA-F-2907806-13214-20230101,Cícero Dantas,BA,Nordeste,2023-01-03 15:14:21,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,52000.0,ATÉ O MOMENTO NÃO AVALIADO DEVIDO A PRECARIEDA...,0.0,0.0,0.0,0.0,0.0,0.0,52000.0,2023
62116,MG-F-3153400-13214-20230101,Presidente Olegário,MG,Sudeste,2023-01-18 17:06:06,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,150000.0,PREJUÍZOS NA AGRICULTURA SENDO ESTA A FRUTICUL...,100000.0,2000000.0,0.0,0.0,0.0,2100000.0,2250000.0,2023
62117,MG-F-3130903-13214-20230101,Inhapim,MG,Sudeste,2023-01-19 11:02:49,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,700000.0,COM QUEDAS DE ESTRAS E PONTES IMPOSSIBILITOU Q...,600000.0,450000.0,0.0,0.0,0.0,1050000.0,1750000.0,2023
62118,MG-F-3128402-13214-20230101,Guarani,MG,Sudeste,2023-01-05 11:25:07,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,0.0,Devido às chuvas intensas ocorridas no municíp...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023
62119,MG-F-3155801-13214-20230101,Rio Pomba,MG,Sudeste,2023-01-05 13:28:49,2023-01-01,13214,13,Chuvas Intensas,Hidrológico,...,2000.0,Devido às chuvas intensas ocorridas no municíp...,0.0,0.0,0.0,0.0,0.0,0.0,2000.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76186,SC-F-4212106-13214-20251231,Palmitos,SC,Sul,2026-01-02 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,90000.0,As chuvas intensas e o elevado escoamento supe...,100000.0,80000.0,0.0,0.0,90000.0,270000.0,360000.0,2025
76187,MG-F-3147907-13214-20251231,Passos,MG,Sudeste,2026-01-06 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,620000.0,As intensas chuvas inviabilizaram as estradas ...,10000.0,10000.0,0.0,0.0,0.0,20000.0,640000.0,2025
76188,SC-F-4212304-13214-20251231,Paulo Lopes,SC,Sul,2026-01-07 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025
76189,SC-F-4216305-13214-20251231,São João Batista,SC,Sul,2026-01-01 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,350000.0,Com efeito do desastre ocasionou a interrupção...,100000.0,0.0,0.0,0.0,0.0,100000.0,450000.0,2025
76190,SC-F-4219606-13214-20251231,Xavantina,SC,Sul,2026-01-19 00:00:00,2025-12-31,13214,13,Chuvas Intensas,Hidrológico,...,2500000.0,Não houve prejuizos privados.,0.0,0.0,0.0,0.0,0.0,0.0,2500000.0,2025

In [126]:
#mapping states to initials
ufs = {'ACRE': 'AC', 'ALAGOAS': 'AL', 'AMAPÁ': 'AP', 'AMAZONAS': 'AM', 'BAHIA': 'BA', 'CEARÁ': 'CE', 'DISTRITO FEDERAL': 'DF', 'ESPÍRITO SANTO': 'ES', 'GOIÁS': 'GO', 'MARANHÃO': 'MA', 'MATO GROSSO': 'MT', 'MATO GROSSO DO SUL': 'MS', 'MINAS GERAIS': 'MG', 'PARÁ': 'PA', 'PARAÍBA': 'PB', 'PARANÁ': 'PR', 'PERNAMBUCO': 'PE', 'PIAUÍ': 'PI', 'RIO DE JANEIRO': 'RJ', 'RIO GRANDE DO NORTE': 'RN', 'RIO GRANDE DO SUL': 'RS', 'RONDÔNIA': 'RO', 'RORAIMA': 'RR', 'SANTA CATARINA': 'SC', 'SÃO PAULO': 'SP', 'SERGIPE': 'SE', 'TOCANTINS': 'TO'}

In [128]:
ambientais['Sigla_UF'] = ambientais['UF'].map(ufs)
estados = pd.concat([
    recentes.groupby('Sigla_UF').size().rename('Eventos'),
    ambientais.groupby('Sigla_UF')['Valor Empenhado'].sum().rename('Valor Empenhado')
], axis=1).fillna(0)

estados['% Eventos'] = (estados['Eventos']/estados['Eventos'].sum() * 100).round(1)
estados['% Dinheiro'] = (estados['Valor Empenhado']/estados['Valor Empenhado'].sum() * 100).round(1)

estados.sort_values('% Eventos', ascending=False)

          Eventos  Valor Empenhado  % Eventos  % Dinheiro
Sigla_UF
RS           1434       9845217.68       24.8         1.9
SC           1183      54084785.00       20.5        10.6
MG            851      21302054.79       14.7         4.2
PA            336             0.00        5.8         0.0
RJ            190      40472528.09        3.3         7.9
SP            185      93258966.51        3.2        18.3
MA            178             0.00        3.1         0.0
PR            174      25030615.12        3.0         4.9
MS            172      33629000.00        3.0         6.6
PE            172      26549452.00        3.0         5.2
BA            162       7788821.26        2.8         1.5
ES            134       4198141.41        2.3         0.8
RN             98      25800694.00        1.7         5.1
CE             92      11805056.46        1.6         2.3
AM             72       2991040.96        1.2         0.6
MT             67      16300000.00        1.2         3.2
AC             56             0.00        1.0         0.0
GO             56       7904743.11        1.0         1.6
AL             46        200000.00        0.8         0.0
PI             33       4020000.00        0.6         0.8
SE             32      28980777.00        0.6         5.7
RO             23       5865000.00        0.4         1.2
AP             13      10000000.00        0.2         2.0
PB              8       5300000.00        0.1         1.0
RR              4             0.00        0.1         0.0
TO              7      72762750.00        0.1        14.3
DF              1       1857616.00        0.0         0.4

In [ ]:
CSV ESTADOS EVENTOS DINHEIRO

In [129]:
estados.to_csv('data/estados_eventos_dinheiro.csv', index=False, sep=';', encoding='utf-8-sig', decimal=',')

In [131]:
#Slope file for Flourish
estados = estados.reset_index()
slope = estados[['Sigla_UF']].copy()
slope['Share of events'] = estados['Eventos'] / estados['Eventos'].sum()*100
slope['Share of money'] = estados['Valor Empenhado'] / estados['Valor Empenhado'].sum() * 100

slope.to_csv('data/slope_estados.csv', index=False)

slope.head()

  Sigla_UF  Share of events  Share of money
0       AC         0.969026        0.000000
1       AL         0.795985        0.039220
2       AM         1.245890        0.586539
3       AP         0.224952        1.960987
4       BA         2.803253        1.527378

## Maps
Municipality boundaries from AdaptaBrasil API

In [132]:
url= "https://sistema.adaptabrasil.mcti.gov.br/api/geometria/data/60001/BR/null/2015/municipio/GEOJSONz/adaptabrasil"
location = requests.get(url).json()['location']
zip_bytes = requests.get(location).content
open('data/dados_brutos/municipios.zip', 'wb').write(zip_bytes)

2654141

In [133]:
import geopandas as gpd

municipios = gpd.read_file('zip://data/dados_brutos/municipios.zip')

municipios.head

<bound method NDFrame.head of         id                           name geocod_ibge  value  \
0        1                       Caiuá/SP     3509106   0.40
1        2                    Castilho/SP     3511003   0.46
2        3                     Dracena/SP     3514403   0.34
3        4            Estrela do Norte/SP     3515301   0.37
4        5  Euclides da Cunha Paulista/SP     3515350   0.39
...    ...                            ...         ...    ...
5565  5568               Teixeirópolis/RO     1101559   0.38
5566  5569                   Theobroma/RO     1101609   0.28
5567  5570                       Urupá/RO     1101708   0.39
5568  5571               Vale do Anari/RO     1101757   0.33
5569  5572             Vale do Paraíso/RO     1101807   0.35

                                                  style  \
0     {'color': '#d7d7d7', 'fillcolor': '#FFCD00', '...
1     {'color': '#d7d7d7', 'fillcolor': '#FFCD00', '...
2     {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
3     {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
4     {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
...                                                 ...
5565  {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
5566  {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
5567  {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
5568  {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...
5569  {'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...

                                               geometry
0     MULTIPOLYGON (((-51.86 -21.5807, -51.8581 -21....
1     MULTIPOLYGON (((-51.42 -20.68, -51.42 -20.69, ...
2     MULTIPOLYGON (((-51.49 -21.43, -51.48 -21.43, ...
3     MULTIPOLYGON (((-51.57 -22.4, -51.57 -22.49, -...
4     MULTIPOLYGON (((-52.45 -22.61, -52.46 -22.61, ...
...                                                 ...
5565  MULTIPOLYGON (((-62.12 -10.9, -62.16 -11, -62....
5566  MULTIPOLYGON (((-61.95 -9.95, -61.96 -9.95, -6...
5567  MULTIPOLYGON (((-62.16 -11.03, -62.16 -11.03, ...
5568  MULTIPOLYGON (((-61.57 -9.72, -61.59 -9.71, -6...
5569  MULTIPOLYGON (((-61.97 -10.07, -61.97 -10.07, ...

[5570 rows x 6 columns]>

In [134]:
municipios.head()

,id,name,geocod_ibge,value,style,geometry
0,1,Caiuá/SP,3509106,0.40,"{'color': '#d7d7d7', 'fillcolor': '#FFCD00', '...","MULTIPOLYGON (((-51.86 -21.5807, -51.8581 -21...."
1,2,Castilho/SP,3511003,0.46,"{'color': '#d7d7d7', 'fillcolor': '#FFCD00', '...","MULTIPOLYGON (((-51.42 -20.68, -51.42 -20.69, ..."
2,3,Dracena/SP,3514403,0.34,"{'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...","MULTIPOLYGON (((-51.49 -21.43, -51.48 -21.43, ..."
3,4,Estrela do Norte/SP,3515301,0.37,"{'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...","MULTIPOLYGON (((-51.57 -22.4, -51.57 -22.49, -..."
4,5,Euclides da Cunha Paulista/SP,3515350,0.39,"{'color': '#d7d7d7', 'fillcolor': '#A9DE00', '...","MULTIPOLYGON (((-52.45 -22.61, -52.46 -22.61, ..."

In [135]:
municipios['geometry'] = municipios.geometry.simplify(0.01)
municipios = municipios[['geocod_ibge', 'geometry']]

In [136]:
mapa = municipios.merge(df_final, left_on='geocod_ibge', right_on='Código IBGE')
mapa.head(10)

,geocod_ibge,geometry,Código IBGE,Município,Índice Deslizamento,Cor Deslizamento,Label Deslizamento,Índice Inundação,Cor Inundação,Label Inundação,Valor Empenhado,Índice Risco Médio,Label Risco Médio
0,3509106,"POLYGON ((-51.86 -21.5807, -51.8429 -21.6131, ...",3509106,Caiuá/SP,0.40,#FFCD00,Médio,0.56,#FFCD00,Médio,NaN,0.480,Medium
1,3511003,"POLYGON ((-51.42 -20.68, -51.45 -20.77, -51.45...",3511003,Castilho/SP,0.46,#FFCD00,Médio,0.58,#FFCD00,Médio,NaN,0.520,Medium
2,3514403,"POLYGON ((-51.49 -21.43, -51.48 -21.53, -51.51...",3514403,Dracena/SP,0.34,#A9DE00,Baixo,0.49,#FFCD00,Médio,NaN,0.415,Medium
3,3515301,"POLYGON ((-51.57 -22.4, -51.57 -22.49, -51.6 -...",3515301,Estrela do Norte/SP,0.37,#A9DE00,Baixo,0.45,#FFCD00,Médio,NaN,0.410,Medium
4,3515350,"POLYGON ((-52.44 -22.61, -52.51 -22.63, -52.54...",3515350,Euclides da Cunha Paulista/SP,0.39,#A9DE00,Baixo,0.48,#FFCD00,Médio,NaN,0.435,Medium
5,3528700,"POLYGON ((-51.92 -22.01, -51.89 -22.01, -51.87...",3528700,Marabá Paulista/SP,0.46,#FFCD00,Médio,0.56,#FFCD00,Médio,NaN,0.510,Medium
6,3530201,"POLYGON ((-51.74 -22.18, -51.74 -22.2, -51.77 ...",3530201,Mirante do Paranapanema/SP,0.50,#FFCD00,Médio,0.70,#FF8300,Alto,NaN,0.600,High
7,3531605,"POLYGON ((-51.5 -21.22, -51.49 -21.25, -51.51 ...",3531605,Monte Castelo/SP,0.35,#A9DE00,Baixo,0.44,#FFCD00,Médio,NaN,0.395,Medium
8,3532207,"POLYGON ((-51.49 -22.36, -51.52 -22.46, -51.47...",3532207,Narandiba/SP,0.22,#A9DE00,Baixo,0.22,#A9DE00,Baixo,NaN,0.220,Low
9,3533106,"POLYGON ((-51.63 -21.32, -51.62 -21.36, -51.67...",3533106,Nova Guataporanga/SP,0.44,#FFCD00,Médio,0.50,#FFCD00,Médio,NaN,0.470,Medium

Map files for Flourish (ive had a lot of help here)

In [137]:
colunas = ['geocod_ibge', 'Município', 'Índice Risco Médio', 'Label Risco Médio', 'geometry']
mapa[colunas].to_file('data/mapa_risco.geojson', driver='GeoJSON')

In [138]:
mapa_alto = mapa[mapa['Label Risco Médio'].isin(['High', 'Very high'])].copy()

mapa_alto['recebeu_ambiental']= mapa_alto['Valor Empenhado'].notna()
mapa_alto['risco_verba'] =(mapa_alto['Índice Risco Médio']== 1.0) &(mapa_alto['Valor Empenhado'].isna())
mapa_alto['Emenda'] = mapa_alto['recebeu_ambiental'].map({True:'Received environmental earmark', False: 'No environmental earmark'})
colunas_alto = colunas +['Valor Empenhado', 'recebeu_ambiental', 'risco_verba', 'Emenda']
mapa_alto[colunas_alto].to_file('data/mapa_risco_alto.geojson', driver='GeoJSON')
len(mapa), len(mapa_alto), mapa_alto['recebeu_ambiental'].sum(), mapa_alto['risco_verba'].sum()

(5570, 1299, np.int64(14), np.int64(4))

## Center points for the marker layers

In [139]:
mapa_alto

,geocod_ibge,geometry,Código IBGE,Município,Índice Deslizamento,Cor Deslizamento,Label Deslizamento,Índice Inundação,Cor Inundação,Label Inundação,Valor Empenhado,Índice Risco Médio,Label Risco Médio,recebeu_ambiental,risco_verba,Emenda
6,3530201,"POLYGON ((-51.74 -22.18, -51.74 -22.2, -51.77 ...",3530201,Mirante do Paranapanema/SP,0.50,#FFCD00,Médio,0.70,#FF8300,Alto,NaN,0.600,High,False,False,No environmental earmark
11,3535408,"POLYGON ((-51.83 -21.37, -51.77 -21.39, -51.75...",3535408,Panorama/SP,0.62,#FF8300,Alto,0.58,#FFCD00,Médio,NaN,0.600,High,False,False,No environmental earmark
13,3538303,"POLYGON ((-51.61 -21.68, -51.62 -21.72, -51.59...",3538303,Piquerobi/SP,0.58,#FFCD00,Médio,0.75,#FF8300,Alto,NaN,0.665,High,False,False,No environmental earmark
14,3541208,"POLYGON ((-51.42 -21.87, -51.42 -21.92, -51.43...",3541208,Presidente Bernardes/SP,0.56,#FFCD00,Médio,0.76,#FF8300,Alto,NaN,0.660,High,False,False,No environmental earmark
21,3547700,"POLYGON ((-51.59 -21.9, -51.55 -21.91, -51.55 ...",3547700,Santo Anastácio/SP,0.52,#FFCD00,Médio,0.69,#FF8300,Alto,NaN,0.605,High,False,False,No environmental earmark
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5513,1304203,"POLYGON ((-64.07 -3.7, -64.08 -3.77, -64.1 -3....",1304203,Tefé/AM,0.79,#FF8300,Alto,0.85,#F40000,Muito alto,NaN,0.820,Very high,False,False,No environmental earmark
5516,1304302,"POLYGON ((-60.04 0.26, -59.19 0.26, -59.19 0.2...",1304302,Urucará/AM,0.81,#F40000,Muito alto,0.73,#FF8300,Alto,NaN,0.770,High,False,False,No environmental earmark
5517,1304401,"POLYGON ((-57.29 -2.49, -57.45 -2.6, -57.43 -2...",1304401,Urucurituba/AM,0.89,#F40000,Muito alto,0.84,#F40000,Muito alto,NaN,0.865,Very high,False,False,No environmental earmark
5532,1100155,"POLYGON ((-62.12 -10.9, -62.31 -10.83, -62.35 ...",1100155,Ouro Preto do Oeste/RO,0.56,#FFCD00,Médio,0.71,#FF8300,Alto,NaN,0.635,High,False,False,No environmental earmark
5533,1100189,"POLYGON ((-60.46 -11.46, -60.47 -11.49, -60.44...",1100189,Pimenta Bueno/RO,0.52,#FFCD00,Médio,0.73,#FF8300,Alto,NaN,0.625,High,False,False,No environmental earmark

In [140]:
pontos = mapa_alto[mapa_alto['recebeu_ambiental']].copy()
pontos['latitude'] = pontos.geometry.representative_point().y
pontos['longitude'] = pontos.geometry.representative_point().x
pontos = pontos[['Município', 'latitude', 'longitude']].rename(columns={'Município': 'name'})

pontos.to_csv('data/pontos_14.csv', index=False)

pontos

                            name   latitude  longitude
1698    Campos dos Goytacazes/RJ -21.640000 -41.325556
1736               Petrópolis/RJ -22.400000 -43.181667
1749           Rio de Janeiro/RJ -22.943377 -43.470174
1754              São Gonçalo/RJ -22.821564 -42.996656
1767              Teresópolis/RJ -22.295000 -42.867500
1769                Três Rios/RJ -22.125000 -43.108375
1837                    Bauru/SP -22.250000 -49.156667
2574                   Canoas/RS -29.895000 -51.182500
2584                   Esteio/RS -29.850000 -51.182500
3898                    Natal/RN  -5.810000 -35.222500
4028           Campina Grande/PB  -7.265000 -35.962500
4287  Jaboatão dos Guararapes/PE  -8.145000 -35.014167
4800                 Salvador/BA -12.880000 -38.483000
5338                  Curiúva/PR -23.995000 -50.470000

In [141]:
pontos4 = mapa_alto[mapa_alto['risco_verba']].copy()

pontos4['latitude'] = pontos4.geometry.representative_point().y
pontos4['longitude'] = pontos4.geometry.representative_point().x

pontos4 = pontos4[['Município', 'latitude', 'longitude']].rename(columns={'Município': 'name'})

pontos4.to_csv('data/pontos_4.csv', index=False)

pontos4

                name  latitude  longitude
4121  Pilõezinhos/PB     -6.86 -35.551000
4204   Água Preta/PE     -8.66 -35.478500
4283       Itambé/PE     -7.44 -35.125833
5026         Afuá/PA     -0.23 -50.740246

In [163]:
#check para
dfemendas[dfemendas['UF'] == 'PARÁ']['Valor Empenhado'].sum()

np.float64(4623611603.61)

In [164]:
recentes[recentes['Sigla_UF'] == 'PA'].shape[0]

336

In [165]:
recentes[recentes['Sigla_UF'] == 'PA']['descricao_tipologia'].value_counts()

descricao_tipologia
Chuvas Intensas       254
Alagamentos            24
Enxurradas             20
Movimento de Massa     19
Inundações             19
Name: count, dtype: int64